version: '3.8'

services:

  db:
    image: postgres:15
    container_name: card-management-db
    environment:
      POSTGRES_DB: card_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    container_name: card-management-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/card_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    command: ["java","-jar","/app/card-management.jar"]
    volumes:
      - ./target:/app

volumes:
  db_data:
